#!/usr/bin/env bash
mkdir -p .testserver/
toml=$(cat pack.toml)
mcver=$(echo "$toml" | tomlq .versions.minecraft | xargs)
fabricver=$(echo "$toml" | tomlq .versions.fabric | xargs)

if [ ! -e .testserver/server.jar -o $(cat .testserver/ver.txt) = "$mcver/$fabricver" ]; then
    wget "https://meta.fabricmc.net/v2/versions/loader/$mcver/$fabricver/1.0.1/server/jar" -O .testserver/server.jar
    echo "$mcver/$fabricver" > .testserver/ver.txt
fi

if [ ! -e .testserver/pw-bs.jar ]; then
    wget "https://github.com/packwiz/packwiz-installer-bootstrap/releases/download/v0.0.3/packwiz-installer-bootstrap.jar" -O .testserver/pw-bs.jar
fi

packwiz serve&
cd .testserver

java -jar pw-bs.jar -s server http://localhost:8080/pack.toml
echo "eula=true" > eula.txt #mojang why ;-;
echo "running server..."
timeout -k 30s 3m java -jar server.jar nogui 2>&1 > /dev/null
status=$?
kill $(jobs -p)

if [ $status -eq 138 -o $status -eq 124 ]; then
    exit 0
else
    echo "FAILED: $status"
    exit 1
fi